-- ============================================================================
-- OLIST E-COMMERCE ANALYTICS - COMPLETE SQL ANALYSIS
-- Database: OLIST_E_COMMERCE | Schema: PUBLIC | Platform: Snowflake
-- Author: Deepanraj A | Data Analyst
-- Date: April 2026
-- ============================================================================

-- ============================================================================
-- SECTION 0: DATA VALIDATION
-- ============================================================================

-- V0: Validate row counts across all views
SELECT 'V_ORDERS' as view_name, COUNT(*) as row_count FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
UNION ALL SELECT 'V_CUSTOMERS', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS
UNION ALL SELECT 'V_ORDER_ITEMS', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS
UNION ALL SELECT 'V_PRODUCTS', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_PRODUCTS
UNION ALL SELECT 'V_PAYMENTS', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS
UNION ALL SELECT 'V_REVIEWS', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_REVIEWS
UNION ALL SELECT 'V_SELLERS', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_SELLERS
UNION ALL SELECT 'V_CATEGORY_TRANSLATION', COUNT(*) FROM OLIST_E_COMMERCE.PUBLIC.V_CATEGORY_TRANSLATION;

-- V1: Null analysis in orders table
SELECT 
    COUNT(*) as total_orders,
    COUNT(CASE WHEN ORDER_APPROVED_AT IS NULL THEN 1 END) as null_approved,
    COUNT(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE IS NULL THEN 1 END) as null_delivered,
    COUNT(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE < ORDER_ESTIMATED_DELIVERY_DATE THEN 1 END) as delivered_on_time,
    COUNT(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE > ORDER_ESTIMATED_DELIVERY_DATE THEN 1 END) as delivered_late
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
WHERE ORDER_STATUS = 'delivered';

-- V2: Date range of dataset
SELECT 
    MIN(ORDER_PURCHASE_TIMESTAMP) as FIRST_ORDER,
    MAX(ORDER_PURCHASE_TIMESTAMP) as LAST_ORDER,
    DATEDIFF('day', MIN(ORDER_PURCHASE_TIMESTAMP), MAX(ORDER_PURCHASE_TIMESTAMP)) as TOTAL_DAYS
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS;

-- ============================================================================
-- SECTION 1: BASIC METRICS (Q1-Q5)
-- ============================================================================

-- Q1: Total Revenue (sum of payment values for delivered orders)
SELECT 
    ROUND(SUM(PAYMENT_VALUE), 2) as TOTAL_REVENUE,
    COUNT(DISTINCT p.ORDER_ID) as TOTAL_ORDERS_WITH_PAYMENT
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON p.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered';

-- Q2: Orders by Status
SELECT 
    ORDER_STATUS, 
    COUNT(*) as order_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) as percentage
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
GROUP BY ORDER_STATUS
ORDER BY order_count DESC;

-- Q3: Total Unique Customers
SELECT 
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) as TOTAL_UNIQUE_CUSTOMERS
FROM OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS;

-- Q4: Total Order Items and Items per Order
SELECT 
    COUNT(*) as TOTAL_ORDER_ITEMS,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    ROUND(COUNT(*) * 1.0 / COUNT(DISTINCT ORDER_ID), 2) as AVG_ITEMS_PER_ORDER
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS;

-- Q5: Orders per Day (Daily Volume)
SELECT 
    DATE_TRUNC('day', ORDER_PURCHASE_TIMESTAMP) as ORDER_DATE,
    COUNT(*) as DAILY_ORDERS
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
GROUP BY 1
ORDER BY 1;

-- ============================================================================
-- SECTION 2: SALES ANALYSIS (Q6-Q11)
-- ============================================================================

-- Q6: Monthly Revenue Trend
SELECT 
    DATE_TRUNC('month', ORDER_PURCHASE_TIMESTAMP) as MONTH,
    ROUND(SUM(PAYMENT_VALUE), 2) as MONTHLY_REVENUE,
    COUNT(DISTINCT o.ORDER_ID) as ORDER_COUNT
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON p.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY 1;

-- Q7: Top 10 Categories by Revenue
SELECT 
    COALESCE(ct.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) as CATEGORY,
    ROUND(SUM(PAYMENT_VALUE), 2) as REVENUE,
    COUNT(DISTINCT o.ORDER_ID) as ORDERS,
    COUNT(DISTINCT p.PRODUCT_ID) as UNIQUE_PRODUCTS
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS pmt
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON pmt.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_CATEGORY_TRANSLATION ct ON p.PRODUCT_CATEGORY_NAME = ct.PRODUCT_CATEGORY_NAME
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY REVENUE DESC
LIMIT 10;

-- Q8: Top 10 Products by Revenue
SELECT 
    oi.PRODUCT_ID,
    COALESCE(ct.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) as CATEGORY,
    ROUND(SUM(oi.PRICE), 2) as REVENUE,
    COUNT(*) as TIMES_SOLD,
    ROUND(AVG(oi.PRICE), 2) as AVG_PRICE
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_CATEGORY_TRANSLATION ct ON p.PRODUCT_CATEGORY_NAME = ct.PRODUCT_CATEGORY_NAME
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1, 2
ORDER BY REVENUE DESC
LIMIT 10;

-- Q9: Revenue by State
SELECT 
    c.CUSTOMER_STATE as STATE,
    ROUND(SUM(PAYMENT_VALUE), 2) as REVENUE,
    COUNT(DISTINCT o.ORDER_ID) as ORDERS
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS pmt
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON pmt.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY REVENUE DESC;

-- Q10: Revenue by Payment Type
SELECT 
    PAYMENT_TYPE,
    ROUND(SUM(PAYMENT_VALUE), 2) as REVENUE,
    COUNT(*) as TRANSACTION_COUNT,
    ROUND(AVG(PAYMENT_VALUE), 2) as AVG_PAYMENT
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON p.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY REVENUE DESC;

-- Q11: Weekly Revenue Trend (Last 8 Weeks)
SELECT 
    DATE_TRUNC('week', ORDER_PURCHASE_TIMESTAMP) as WEEK,
    ROUND(SUM(PAYMENT_VALUE), 2) as WEEKLY_REVENUE,
    COUNT(DISTINCT o.ORDER_ID) as ORDER_COUNT
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON p.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY 1 DESC
LIMIT 8;

-- ============================================================================
-- SECTION 3: CUSTOMER ANALYSIS (Q12-Q17)
-- ============================================================================

-- Q12: New vs Repeat Customers (by year)
WITH customer_orders AS (
    SELECT 
        CUSTOMER_UNIQUE_ID,
        YEAR(ORDER_PURCHASE_TIMESTAMP) as order_year,
        COUNT(DISTINCT o.ORDER_ID) as orders_per_year
    FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS o
    JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
    GROUP BY 1, 2
)
SELECT 
    order_year,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) as TOTAL_CUSTOMERS,
    SUM(CASE WHEN orders_per_year = 1 THEN 1 ELSE 0 END) as NEW_CUSTOMERS,
    SUM(CASE WHEN orders_per_year > 1 THEN 1 ELSE 0 END) as REPEAT_CUSTOMERS,
    ROUND(SUM(CASE WHEN orders_per_year > 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(DISTINCT CUSTOMER_UNIQUE_ID), 2) as REPEAT_RATE_PCT
FROM customer_orders
GROUP BY 1
ORDER BY 1;

-- Q13: Customer Retention Rate (Cohort Analysis)
WITH first_order AS (
    SELECT 
        CUSTOMER_UNIQUE_ID,
        MIN(ORDER_PURCHASE_TIMESTAMP) as FIRST_ORDER_DATE
    FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS o
    JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
    GROUP BY 1
),
cohort AS (
    SELECT 
        CUSTOMER_UNIQUE_ID,
        DATE_TRUNC('month', FIRST_ORDER_DATE) as COHORT_MONTH,
        DATEDIFF('month', FIRST_ORDER_DATE, ORDER_PURCHASE_TIMESTAMP) as MONTHS_SINCE_FIRST
    FROM first_order f
    JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON f.CUSTOMER_UNIQUE_ID = o.CUSTOMER_ID
)
SELECT 
    COHORT_MONTH,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) as TOTAL_CUSTOMERS,
    COUNT(DISTINCT CASE WHEN MONTHS_SINCE_FIRST = 1 THEN CUSTOMER_UNIQUE_ID END) as MONTH_1_RETAINED,
    ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_FIRST = 1 THEN CUSTOMER_UNIQUE_ID END) * 100.0 / COUNT(DISTINCT CUSTOMER_UNIQUE_ID), 2) as RETENTION_RATE_PCT
FROM cohort
GROUP BY 1
ORDER BY 1
LIMIT 12;

-- Q14: Top 10 High-Value Customers (by total spend)
SELECT 
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_CITY,
    c.CUSTOMER_STATE,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    ROUND(SUM(PAYMENT_VALUE), 2) as TOTAL_SPEND,
    ROUND(SUM(PAYMENT_VALUE) / COUNT(DISTINCT o.ORDER_ID), 2) as AVG_ORDER_VALUE
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON p.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1, 2, 3
ORDER BY TOTAL_SPEND DESC
LIMIT 10;

-- Q15: Customer Geographic Distribution (Top 20 Cities)
SELECT 
    CUSTOMER_STATE as STATE,
    CUSTOMER_CITY as CITY,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) as UNIQUE_CUSTOMERS,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS o
JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY 1, 2
ORDER BY UNIQUE_CUSTOMERS DESC
LIMIT 20;

-- Q16: Orders per Customer Distribution
SELECT 
    orders_count as ORDERS_PER_CUSTOMER,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) as CUSTOMER_COUNT
FROM (
    SELECT 
        CUSTOMER_UNIQUE_ID,
        COUNT(DISTINCT o.ORDER_ID) as orders_count
    FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS o
    JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
    GROUP BY 1
)
GROUP BY 1
ORDER BY 1;

-- Q17: Average Order Value by State
SELECT 
    CUSTOMER_STATE as STATE,
    ROUND(AVG(PAYMENT_VALUE), 2) as AVG_ORDER_VALUE,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    ROUND(SUM(PAYMENT_VALUE), 2) as TOTAL_REVENUE
FROM OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON p.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY AVG_ORDER_VALUE DESC;

-- ============================================================================
-- SECTION 4: DELIVERY ANALYSIS (Q18-Q22)
-- ============================================================================

-- Q18: Average Delivery Time Statistics
SELECT 
    ROUND(AVG(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as AVG_DELIVERY_DAYS,
    MIN(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)) as MIN_DELIVERY_DAYS,
    MAX(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)) as MAX_DELIVERY_DAYS,
    ROUND(MEDIAN(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as MEDIAN_DELIVERY_DAYS,
    ROUND(STDDEV(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as STDDEV_DELIVERY_DAYS
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
WHERE ORDER_STATUS = 'delivered' AND ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL;

-- Q19: Late Delivery Percentage
SELECT 
    COUNT(*) as TOTAL_DELIVERED,
    SUM(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE > ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) as LATE_DELIVERIES,
    ROUND(SUM(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE > ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as LATE_DELIVERY_PCT,
    SUM(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE <= ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) as ON_TIME_DELIVERIES,
    ROUND(SUM(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE <= ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as ON_TIME_PCT
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
WHERE ORDER_STATUS = 'delivered' AND ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL;

-- Q20: Delivery Time by Category (Top 15)
SELECT 
    COALESCE(ct.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) as CATEGORY,
    ROUND(AVG(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as AVG_DELIVERY_DAYS,
    COUNT(DISTINCT o.ORDER_ID) as ORDERS,
    ROUND(AVG(oi.PRICE), 2) as AVG_ITEM_PRICE
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_CATEGORY_TRANSLATION ct ON p.PRODUCT_CATEGORY_NAME = ct.PRODUCT_CATEGORY_NAME
WHERE o.ORDER_STATUS = 'delivered' AND ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY 1
ORDER BY AVG_DELIVERY_DAYS DESC
LIMIT 15;

-- Q21: Delivery Delay by Seller (Top performers and worst)
WITH seller_delivery AS (
    SELECT 
        s.SELLER_ID,
        s.SELLER_CITY,
        s.SELLER_STATE,
        COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
        ROUND(AVG(DATEDIFF('day', ORDER_ESTIMATED_DELIVERY_DATE, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as AVG_DELAY_DAYS,
        SUM(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE > ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) as LATE_COUNT,
        ROUND(SUM(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE > ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) * 100.0 / COUNT(DISTINCT o.ORDER_ID), 2) as LATE_PCT
    FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi
    JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
    JOIN OLIST_E_COMMERCE.PUBLIC.V_SELLERS s ON oi.SELLER_ID = s.SELLER_ID
    WHERE o.ORDER_STATUS = 'delivered' AND ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
    GROUP BY 1, 2, 3
    HAVING COUNT(DISTINCT o.ORDER_ID) >= 100
)
SELECT *, 'BEST' as PERFORMANCE FROM seller_delivery ORDER BY AVG_DELAY_DAYS ASC LIMIT 10
UNION ALL
SELECT *, 'WORST' as PERFORMANCE FROM seller_delivery ORDER BY AVG_DELAY_DAYS DESC LIMIT 10;

-- Q22: Delivery Time Trend by Month
SELECT 
    DATE_TRUNC('month', ORDER_PURCHASE_TIMESTAMP) as MONTH,
    ROUND(AVG(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as AVG_DELIVERY_DAYS,
    COUNT(DISTINCT ORDER_ID) as ORDERS,
    ROUND(MEDIAN(DATEDIFF('day', ORDER_PURCHASE_TIMESTAMP, ORDER_DELIVERED_CUSTOMER_DATE)), 2) as MEDIAN_DELIVERY_DAYS
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS
WHERE ORDER_STATUS = 'delivered' AND ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY 1
ORDER BY 1;

-- ============================================================================
-- SECTION 5: REVIEW ANALYSIS (Q23-Q27)
-- ============================================================================

-- Q23: Overall Review Statistics
SELECT 
    COUNT(*) as TOTAL_REVIEWS,
    COUNT(DISTINCT ORDER_ID) as ORDERS_WITH_REVIEWS,
    ROUND(AVG(REVIEW_SCORE), 2) as AVG_RATING,
    ROUND(MEDIAN(REVIEW_SCORE), 2) as MEDIAN_RATING,
    ROUND(MIN(REVIEW_SCORE), 2) as MIN_RATING,
    ROUND(MAX(REVIEW_SCORE), 2) as MAX_RATING
FROM OLIST_E_COMMERCE.PUBLIC.V_REVIEWS;

-- Q24: Rating Distribution
SELECT 
    REVIEW_SCORE as RATING,
    COUNT(*) as REVIEW_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) as PERCENTAGE
FROM OLIST_E_COMMERCE.PUBLIC.V_REVIEWS
GROUP BY 1
ORDER BY 1;

-- Q25: Reviews by Month
SELECT 
    DATE_TRUNC('month', REVIEW_CREATION_DATE) as MONTH,
    COUNT(*) as TOTAL_REVIEWS,
    ROUND(AVG(REVIEW_SCORE), 2) as AVG_RATING
FROM OLIST_E_COMMERCE.PUBLIC.V_REVIEWS
GROUP BY 1
ORDER BY 1;

-- Q26: Rating Impact on Repeat Purchases (Using Window Functions)
WITH customer_ratings AS (
    SELECT 
        o.CUSTOMER_ID,
        r.REVIEW_SCORE,
        r.REVIEW_CREATION_DATE,
        LAG(r.REVIEW_SCORE) OVER (PARTITION BY o.CUSTOMER_ID ORDER BY r.REVIEW_CREATION_DATE) as PREV_RATING,
        COUNT(DISTINCT o.ORDER_ID) OVER (PARTITION BY o.CUSTOMER_ID) as TOTAL_CUSTOMER_ORDERS
    FROM OLIST_E_COMMERCE.PUBLIC.V_REVIEWS r
    JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON r.ORDER_ID = o.ORDER_ID
)
SELECT 
    CASE WHEN PREV_RATING >= 4 THEN 'High Rating Customer' ELSE 'Low Rating Customer' END as CUSTOMER_SEGMENT,
    AVG(REVIEW_SCORE) as AVG_RATING,
    AVG(TOTAL_CUSTOMER_ORDERS) as AVG_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) as CUSTOMER_COUNT
FROM customer_ratings
WHERE PREV_RATING IS NOT NULL
GROUP BY 1
ORDER BY AVG_RATING DESC;

-- Q27: Reviews vs Delivery Delay Correlation
SELECT 
    CASE 
        WHEN DATEDIFF('day', o.ORDER_ESTIMATED_DELIVERY_DATE, o.ORDER_DELIVERED_CUSTOMER_DATE) <= 0 THEN 'On Time or Early'
        WHEN DATEDIFF('day', o.ORDER_ESTIMATED_DELIVERY_DATE, o.ORDER_DELIVERED_CUSTOMER_DATE) <= 5 THEN '1-5 Days Late'
        ELSE 'More than 5 Days Late'
    END as DELIVERY_CATEGORY,
    COUNT(*) as ORDER_COUNT,
    ROUND(AVG(r.REVIEW_SCORE), 2) as AVG_RATING,
    ROUND(MEDIAN(r.REVIEW_SCORE), 2) as MEDIAN_RATING
FROM OLIST_E_COMMERCE.PUBLIC.V_REVIEWS r
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON r.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY 1
ORDER BY 1;

-- ============================================================================
-- SECTION 6: ADVANCED ANALYTICS (Q28-Q30)
-- ============================================================================

-- Q28: Customer Lifetime Value Segmentation (RFM Analysis)
WITH rfm_base AS (
    SELECT 
        o.CUSTOMER_ID,
        MAX(ORDER_PURCHASE_TIMESTAMP) as LAST_ORDER_DATE,
        COUNT(DISTINCT o.ORDER_ID) as FREQUENCY,
        SUM(PAYMENT_VALUE) as MONETARY
    FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS o
    JOIN OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS p ON o.ORDER_ID = p.ORDER_ID
    WHERE o.ORDER_STATUS = 'delivered'
    GROUP BY 1
),
rfm_calc AS (
    SELECT 
        CUSTOMER_ID,
        DATEDIFF('day', LAST_ORDER_DATE, (SELECT MAX(ORDER_PURCHASE_TIMESTAMP) FROM OLIST_E_COMMERCE.PUBLIC.V_ORDERS)) as RECENCY,
        FREQUENCY,
        MONETARY,
        NTILE(4) OVER (ORDER BY RECENCY DESC) as R_SCORE,
        NTILE(4) OVER (ORDER BY FREQUENCY ASC) as F_SCORE,
        NTILE(4) OVER (ORDER BY MONETARY ASC) as M_SCORE
    FROM rfm_base
)
SELECT 
    CONCAT(R_SCORE, F_SCORE, M_SCORE) as RFM_SEGMENT,
    CASE 
        WHEN R_SCORE >= 3 AND F_SCORE >= 3 AND M_SCORE >= 3 THEN 'Champions'
        WHEN R_SCORE >= 3 AND F_SCORE >= 2 THEN 'Loyal Customers'
        WHEN R_SCORE >= 3 AND M_SCORE >= 3 THEN 'Big Spenders'
        WHEN R_SCORE <= 2 AND F_SCORE <= 2 AND M_SCORE <= 2 THEN 'At Risk'
        WHEN R_SCORE <= 2 THEN 'Lost'
        ELSE 'Regular'
    END as CUSTOMER_TIER,
    COUNT(*) as CUSTOMER_COUNT,
    ROUND(AVG(RECENCY), 0) as AVG_RECENCY,
    ROUND(AVG(FREQUENCY), 1) as AVG_FREQUENCY,
    ROUND(AVG(MONETARY), 2) as AVG_MONETARY
FROM rfm_calc
GROUP BY 1, 2
ORDER BY AVG_MONETARY DESC;

-- Q29: Product Performance with Inventory Insights
SELECT 
    oi.PRODUCT_ID,
    COALESCE(ct.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) as CATEGORY,
    COUNT(*) as TIMES_SOLD,
    ROUND(SUM(oi.PRICE), 2) as TOTAL_REVENUE,
    ROUND(AVG(oi.PRICE), 2) as AVG_PRICE,
    p.PRODUCT_PHOTOS_QTY,
    p.PRODUCT_WEIGHT_G,
    ROUND(p.PRODUCT_LENGTH_CM * p.PRODUCT_WIDTH_CM * p.PRODUCT_HEIGHT_CM, 0) as PRODUCT_VOLUME_CM3,
    ROUND(AVG(DATEDIFF('day', o.ORDER_PURCHASE_TIMESTAMP, o.ORDER_DELIVERED_CUSTOMER_DATE)), 1) as AVG_DELIVERY_DAYS,
    ROUND(AVG(r.REVIEW_SCORE), 2) as AVG_RATING
FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_CATEGORY_TRANSLATION ct ON p.PRODUCT_CATEGORY_NAME = ct.PRODUCT_CATEGORY_NAME
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_REVIEWS r ON o.ORDER_ID = r.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered' AND o.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY 1, 2, 6, 7, 8
HAVING COUNT(*) >= 10
ORDER BY TOTAL_REVENUE DESC
LIMIT 20;

-- Q30: Seller Performance Score
WITH seller_metrics AS (
    SELECT 
        s.SELLER_ID,
        s.SELLER_CITY,
        s.SELLER_STATE,
        COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
        ROUND(SUM(oi.PRICE), 2) as TOTAL_REVENUE,
        ROUND(AVG(DATEDIFF('day', o.ORDER_ESTIMATED_DELIVERY_DATE, o.ORDER_DELIVERED_CUSTOMER_DATE)), 2) as AVG_DELAY,
        ROUND(AVG(r.REVIEW_SCORE), 2) as AVG_RATING,
        COUNT(DISTINCT oi.PRODUCT_ID) as UNIQUE_PRODUCTS,
        COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS
    FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi
    JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
    JOIN OLIST_E_COMMERCE.PUBLIC.V_SELLERS s ON oi.SELLER_ID = s.SELLER_ID
    LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_REVIEWS r ON o.ORDER_ID = r.ORDER_ID
    WHERE o.ORDER_STATUS = 'delivered' AND o.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
    GROUP BY 1, 2, 3
    HAVING COUNT(DISTINCT o.ORDER_ID) >= 50
)
SELECT 
    *,
    ROUND((AVG_RATING * 20) - (ABS(AVG_DELAY) * 2) + (TOTAL_ORDERS / 100), 2) as SELLER_PERFORMANCE_SCORE
FROM seller_metrics
ORDER BY SELLER_PERFORMANCE_SCORE DESC
LIMIT 20;

-- ============================================================================
-- SECTION 7: FINAL DASHBOARD VIEW (Power BI Ready)
-- ============================================================================

-- Create the final denormalized dashboard view for Power BI
CREATE OR REPLACE VIEW OLIST_E_COMMERCE.PUBLIC.FINAL_DASHBOARD AS
SELECT 
    o.ORDER_ID,
    o.ORDER_STATUS,
    o.ORDER_PURCHASE_TIMESTAMP,
    DATE_TRUNC('month', o.ORDER_PURCHASE_TIMESTAMP) as ORDER_MONTH,
    DATE_TRUNC('quarter', o.ORDER_PURCHASE_TIMESTAMP) as ORDER_QUARTER,
    YEAR(o.ORDER_PURCHASE_TIMESTAMP) as ORDER_YEAR,
    DATE_TRUNC('week', o.ORDER_PURCHASE_TIMESTAMP) as ORDER_WEEK,
    o.ORDER_APPROVED_AT,
    o.ORDER_DELIVERED_CARRIER_DATE,
    o.ORDER_DELIVERED_CUSTOMER_DATE,
    o.ORDER_ESTIMATED_DELIVERY_DATE,
    
    -- Delivery Metrics
    DATEDIFF('day', o.ORDER_PURCHASE_TIMESTAMP, o.ORDER_DELIVERED_CUSTOMER_DATE) as DELIVERY_DAYS,
    DATEDIFF('day', o.ORDER_ESTIMATED_DELIVERY_DATE, o.ORDER_DELIVERED_CUSTOMER_DATE) as DELAY_DAYS,
    CASE 
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE IS NULL THEN 'Not Delivered'
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE <= o.ORDER_ESTIMATED_DELIVERY_DATE THEN 'On Time'
        ELSE 'Late'
    END as DELIVERY_STATUS,
    
    -- Customer Dimension
    c.CUSTOMER_ID,
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_CITY,
    c.CUSTOMER_STATE,
    c.CUSTOMER_ZIP_CODE_PREFIX,
    
    -- Order Items (Fact)
    oi.ORDER_ITEM_ID,
    oi.PRODUCT_ID,
    oi.SELLER_ID,
    oi.SHIPPING_LIMIT_DATE,
    oi.PRICE as ITEM_PRICE,
    oi.FREIGHT_VALUE,
    oi.PRICE + oi.FREIGHT_VALUE as TOTAL_ITEM_VALUE,
    
    -- Product Dimension
    p.PRODUCT_CATEGORY_NAME as CATEGORY_PORTUGUESE,
    COALESCE(ct.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME) as CATEGORY,
    p.PRODUCT_NAME_LENGTH,
    p.PRODUCT_DESCRIPTION_LENGTH,
    p.PRODUCT_PHOTOS_QTY,
    p.PRODUCT_WEIGHT_G,
    p.PRODUCT_LENGTH_CM,
    p.PRODUCT_HEIGHT_CM,
    p.PRODUCT_WIDTH_CM,
    
    -- Seller Dimension
    s.SELLER_CITY as SELLER_CITY,
    s.SELLER_STATE as SELLER_STATE,
    
    -- Payment Info (aggregated per order)
    pmt.PAYMENT_TYPE,
    pmt.PAYMENT_INSTALLMENTS,
    pmt.PAYMENT_VALUE,
    
    -- Review Info (aggregated per order)
    r.REVIEW_ID,
    r.REVIEW_SCORE,
    r.REVIEW_CREATION_DATE,
    r.REVIEW_COMMENT_TITLE,
    r.REVIEW_COMMENT_MESSAGE

FROM OLIST_E_COMMERCE.PUBLIC.V_ORDER_ITEMS oi
JOIN OLIST_E_COMMERCE.PUBLIC.V_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN OLIST_E_COMMERCE.PUBLIC.V_SELLERS s ON oi.SELLER_ID = s.SELLER_ID
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_CATEGORY_TRANSLATION ct ON p.PRODUCT_CATEGORY_NAME = ct.PRODUCT_CATEGORY_NAME
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_PAYMENTS pmt ON o.ORDER_ID = pmt.ORDER_ID
LEFT JOIN OLIST_E_COMMERCE.PUBLIC.V_REVIEWS r ON o.ORDER_ID = r.ORDER_ID;

-- ============================================================================
-- SECTION 8: VERIFICATION QUERIES
-- ============================================================================

-- Verify FINAL_DASHBOARD was created
SELECT COUNT(*) as TOTAL_ROWS, COUNT(DISTINCT ORDER_ID) as UNIQUE_ORDERS
FROM OLIST_E_COMMERCE.PUBLIC.FINAL_DASHBOARD;

-- Sample from FINAL_DASHBOARD
SELECT * FROM OLIST_E_COMMERCE.PUBLIC.FINAL_DASHBOARD LIMIT 10;

-- Monthly KPI Summary from FINAL_DASHBOARD
SELECT 
    ORDER_MONTH,
    COUNT(DISTINCT ORDER_ID) as TOTAL_ORDERS,
    ROUND(SUM(PAYMENT_VALUE), 2) as TOTAL_REVENUE,
    ROUND(AVG(PAYMENT_VALUE), 2) as AVG_ORDER_VALUE,
    ROUND(AVG(DELIVERY_DAYS), 1) as AVG_DELIVERY_DAYS,
    ROUND(AVG(REVIEW_SCORE), 2) as AVG_RATING,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) as UNIQUE_CUSTOMERS
FROM OLIST_E_COMMERCE.PUBLIC.FINAL_DASHBOARD
WHERE ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY 1;

-- ============================================================================
-- END OF SQL ANALYSIS SCRIPT
-- Author: Deepanraj A | Data Analyst
-- Total Queries: 33 | Total Views Created: 1 (FINAL_DASHBOARD)
-- ============================================================================
